
hull:  hull.c Makefile ../lib/dynamic_array/dynamic_array.c ../lib/utils/merge_sort.c ../lib/utils/remove_repeated.c ../lib/line/line.c ../lib/point/point.c ../lib/polygon/polygon.c
	gcc -g -O0 -Wall -Wextra -lm ../lib/dynamic_array/dynamic_array.c ../lib/utils/merge_sort.c ../lib/utils/remove_repeated.c ../lib/line/line.c ../lib/point/point.c ../lib/polygon/polygon.c -o hull hull.c

prod:
	gcc -O3 -Wall -Wextra -lm ../lib/dynamic_array/dynamic_array.c ../lib/utils/merge_sort.c ../lib/utils/remove_repeated.c ../lib/line/line.c ../lib/point/point.c ../lib/polygon/polygon.c -o hull hull.c
