hull:  hull.c Makefile ../lib/dynamic_array/dynamic_array.c ../lib/dynamic_array/merge_sort_diff.c ../lib/line/line.c ../lib/point/point.c ../lib/polygon/polygon.c
	gcc -g -O0 -Wall -Wextra -lm ../lib/dynamic_array/dynamic_array.c ../lib/dynamic_array/merge_sort_diff.c ../lib/line/line.c ../lib/point/point.c ../lib/polygon/polygon.c -o hull hull.c

